/* AUTOGENERATED -> DO NOT EDIT OR YOUR EDITS WILL BE LOST! */
#ifndef @OBJECT@_GLIB_OBJ_H
#define @OBJECT@_GLIB_OBJ_H

#include <glib.h>
#include <glib-object.h>
#include <dbus/dbus.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <xcdbus.h>

@CONSTANTS@

typedef struct @GLIB_OBJ@ { GObject parent; } @GLIB_OBJ@;
typedef struct @GLIB_CLASS@ { GObjectClass parent; } @GLIB_CLASS@;

#define @OBJECT@_TYPE_OBJECT              (@object@_object_get_type ())
#define @OBJECT@_OBJECT(object)           (G_TYPE_CHECK_INSTANCE_CAST ((object), @OBJECT@_TYPE_OBJECT, @GLIB_OBJ@))
#define @OBJECT@_OBJECT_CLASS(klass)      (G_TYPE_CHECK_CLASS_CAST ((klass), @OBJECT@_TYPE_OBJECT, @GLIB_CLASS@))
#define @OBJECT@_IS_OBJECT(object)        (G_TYPE_CHECK_INSTANCE_TYPE ((object), @OBJECT@_TYPE_OBJECT))
#define @OBJECT@_IS_OBJECT_CLASS(klass)   (G_TYPE_CHECK_CLASS_TYPE ((klass), @OBJECT@_TYPE_OBJECT))
#define @OBJECT@_OBJECT_GET_CLASS(obj)    (G_TYPE_INSTANCE_GET_CLASS ((obj), @OBJECT@_TYPE_OBJECT, @GLIB_CLASS@))

/* export server object over dbus at given PATH */
extern @GLIB_OBJ@ *@object@_export_dbus(DBusGConnection *conn, const char *path);

/* SIGNALS -> call to raise */
@SIGNALS@

/* SERVER OBJECT PROTOTYPES -> IMPLEMENT THESE */
@PROTOTYPES@

#endif
