(* THIS FILE IS AUTOGENERATED -> DO NOT EDIT OR YOUR EDITS WILL BE LOST! *)
open DBus

let bus = DBus.Bus.get DBus.Bus.System
let default_timeout = 1000 * 3600 (* one hour *)

let call_dbus ~timeout ~service ~obj ~interface ~member ~args =
	let m = DBus.Message.new_method_call service obj interface member in
	ignore (DBus.Message.append m args);
	DBus.Connection.send_with_reply_and_block bus m ( if timeout>0 then timeout * 1000 else default_timeout )

@STUBS@

