-- THIS FILE IS AUTOGENERATED -> DO NOT EDIT OR YOUR EDITS WILL BE LOST!
module @MODULE@ (
@MODULE_EXPORTS@
) where

import Data.Maybe
import Data.String
import Data.Int
import Data.Word
import qualified Data.Map as Map
import qualified Data.Text.Lazy as TL
import qualified Data.ByteString as B
import Rpc.Core

-- TODO: drop usage of raw strings
mkcall :: String -> String -> String -> String -> [Variant] -> RpcCall
mkcall service objpath interface memb args =
  RpcCall (fromString service) (fromString objpath) (fromString interface) (fromString memb) args

@METHODS@
