-- THIS FILE IS AUTOGENERATED -> DO NOT EDIT OR YOUR EDITS WILL BE LOST!
module @MODULE@ (
@MODULE_EXPORTS@
) where

import Data.String
import Data.Word
import Data.Int
import Data.Maybe
import qualified Data.Map as Map
import Rpc.Core

@CONSTS@
