/* AUTOGENERATED -> DO NOT EDIT OR YOUR EDITS WILL BE LOST! */
#ifndef @OBJECT@_CLIENT_H
#define @OBJECT@_CLIENT_H

#include <glib.h>
#include <glib-object.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <xcdbus.h>

@CONSTANTS@

/* prototypes generated by dbus-binding-tool */
@BINDING_TOOL_OUTPUT@

/* prototypes which do the proxy creation for us */
@PROXY_PROTOTYPES@

#endif
